//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ttcm
{
    using System;
    using System.Collections.Generic;
    
    public partial class cthoadon
    {
        public string Machitiet { get; set; }
        public string MaHoadon { get; set; }
        public string masanpham { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
