//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ttcm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBanXeEntities1 : DbContext
    {
        public QLBanXeEntities1()
            : base("name=QLBanXeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cthoadon> cthoadons { get; set; }
        public virtual DbSet<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LoaiTK> LoaiTKs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual int danhmuc123(string tennhom)
        {
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("danhmuc123", tennhomParameter);
        }
    
        public virtual int insertctphieunhap(string masp, Nullable<int> gianhap, Nullable<int> soluong, Nullable<int> thanhthien)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var gianhapParameter = gianhap.HasValue ?
                new ObjectParameter("gianhap", gianhap) :
                new ObjectParameter("gianhap", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thanhthienParameter = thanhthien.HasValue ?
                new ObjectParameter("thanhthien", thanhthien) :
                new ObjectParameter("thanhthien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertctphieunhap", maspParameter, gianhapParameter, soluongParameter, thanhthienParameter);
        }
    
        public virtual int insertKH(string tenkh, Nullable<System.DateTime> ngaysinh, Nullable<int> sdt, string gmail)
        {
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var gmailParameter = gmail != null ?
                new ObjectParameter("Gmail", gmail) :
                new ObjectParameter("Gmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertKH", tenkhParameter, ngaysinhParameter, sdtParameter, gmailParameter);
        }
    
        public virtual int insertNV(string tennv, string chucvu, Nullable<System.DateTime> ngayvaolam, Nullable<int> luong, string gmail, Nullable<int> sdt)
        {
            var tennvParameter = tennv != null ?
                new ObjectParameter("tennv", tennv) :
                new ObjectParameter("tennv", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            var ngayvaolamParameter = ngayvaolam.HasValue ?
                new ObjectParameter("ngayvaolam", ngayvaolam) :
                new ObjectParameter("ngayvaolam", typeof(System.DateTime));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(int));
    
            var gmailParameter = gmail != null ?
                new ObjectParameter("Gmail", gmail) :
                new ObjectParameter("Gmail", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertNV", tennvParameter, chucvuParameter, ngayvaolamParameter, luongParameter, gmailParameter, sdtParameter);
        }
    
        public virtual int insertSP(string tensp, string manhom, Nullable<int> giaban, Nullable<int> soluongton, byte[] hinhanh)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var manhomParameter = manhom != null ?
                new ObjectParameter("manhom", manhom) :
                new ObjectParameter("manhom", typeof(string));
    
            var giabanParameter = giaban.HasValue ?
                new ObjectParameter("giaban", giaban) :
                new ObjectParameter("giaban", typeof(int));
    
            var soluongtonParameter = soluongton.HasValue ?
                new ObjectParameter("soluongton", soluongton) :
                new ObjectParameter("soluongton", typeof(int));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertSP", tenspParameter, manhomParameter, giabanParameter, soluongtonParameter, hinhanhParameter);
        }
    
        public virtual int inssertdanhmuc(string tennhom)
        {
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inssertdanhmuc", tennhomParameter);
        }
    
        public virtual int INSSERTPN(Nullable<System.DateTime> ngaylappn, Nullable<int> tongtien, string tinhtrang, string mancc, string manv)
        {
            var ngaylappnParameter = ngaylappn.HasValue ?
                new ObjectParameter("ngaylappn", ngaylappn) :
                new ObjectParameter("ngaylappn", typeof(System.DateTime));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSSERTPN", ngaylappnParameter, tongtienParameter, tinhtrangParameter, manccParameter, manvParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int inssertCThoadon(string machitiet, string mahoadon, string masanpham, Nullable<int> soluong, Nullable<int> tongtien)
        {
            var machitietParameter = machitiet != null ?
                new ObjectParameter("Machitiet", machitiet) :
                new ObjectParameter("Machitiet", typeof(string));
    
            var mahoadonParameter = mahoadon != null ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(string));
    
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inssertCThoadon", machitietParameter, mahoadonParameter, masanphamParameter, soluongParameter, tongtienParameter);
        }
    
        public virtual int insertctphieunhap123(string mapn, string masp, Nullable<int> gianhap, Nullable<int> soluong, Nullable<int> thanhtien)
        {
            var mapnParameter = mapn != null ?
                new ObjectParameter("mapn", mapn) :
                new ObjectParameter("mapn", typeof(string));
    
            var maspParameter = masp != null ?
                new ObjectParameter("Masp", masp) :
                new ObjectParameter("Masp", typeof(string));
    
            var gianhapParameter = gianhap.HasValue ?
                new ObjectParameter("gianhap", gianhap) :
                new ObjectParameter("gianhap", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertctphieunhap123", mapnParameter, maspParameter, gianhapParameter, soluongParameter, thanhtienParameter);
        }
    
        public virtual int update_Hd(string mahd, Nullable<int> tongtien)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Hd", mahdParameter, tongtienParameter);
        }
    
        public virtual ObjectResult<seaching_nv_Result> seaching_nv(string valuaToFind)
        {
            var valuaToFindParameter = valuaToFind != null ?
                new ObjectParameter("valuaToFind", valuaToFind) :
                new ObjectParameter("valuaToFind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaching_nv_Result>("seaching_nv", valuaToFindParameter);
        }
    
        public virtual ObjectResult<seaching_tongtienthang_Result> seaching_tongtienthang(string valuaToFind)
        {
            var valuaToFindParameter = valuaToFind != null ?
                new ObjectParameter("valuaToFind", valuaToFind) :
                new ObjectParameter("valuaToFind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaching_tongtienthang_Result>("seaching_tongtienthang", valuaToFindParameter);
        }
    
        public virtual ObjectResult<seaching_tongtienthang1_Result> seaching_tongtienthang1(string valuaToFind)
        {
            var valuaToFindParameter = valuaToFind != null ?
                new ObjectParameter("valuaToFind", valuaToFind) :
                new ObjectParameter("valuaToFind", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaching_tongtienthang1_Result>("seaching_tongtienthang1", valuaToFindParameter);
        }
    
        public virtual int updatePhieuNhap(string maphieunhap, Nullable<int> tongtien)
        {
            var maphieunhapParameter = maphieunhap != null ?
                new ObjectParameter("maphieunhap", maphieunhap) :
                new ObjectParameter("maphieunhap", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatePhieuNhap", maphieunhapParameter, tongtienParameter);
        }
    
        public virtual ObjectResult<dt_Result> dt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_Result>("dt");
        }
    
        public virtual ObjectResult<dttn_Result> dttn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dttn_Result>("dttn");
        }
    }
}
